apiVersion: v1
kind: Service
metadata:
  name: mcp-ryot
  namespace: mcp-arr
  labels:
    app.kubernetes.io/name: mcp-ryot
    app.kubernetes.io/part-of: mcp-arr
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.253.66
  selector:
    app.kubernetes.io/name: mcp-ryot
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
