apiVersion: v1
kind: Service
metadata:
  name: midia-mcp
  namespace: ia-mcp
  labels:
    app.kubernetes.io/name: midia-mcp
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: midia-mcp
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
