apiVersion: v1
kind: Service
metadata:
  name: midia-mcp
  namespace: mcp-arr
  labels:
    app.kubernetes.io/name: midia-mcp
spec:
  type: LoadBalancer
  loadBalancerIP: "192.168.253.41"
  selector:
    app.kubernetes.io/name: midia-mcp
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
