transport: streamable-http
host: "0.0.0.0"
port: 3000

services:
  mal:
    client_id: "YOUR_MAL_CLIENT_ID_HERE"

  searxng:
    url: "http://searxng:8080"

auth_tokens:
  - token: "admin-GENERATE_WITH_openssl_rand_hex_32"
    description: "Admin"
    permissions:
      mal: { actions: ["*"] }
