transport: streamable-http
host: "0.0.0.0"
port: 3000

services:
  ryot:
    url: "http://ryot:8000"
    api_token: "YOUR_RYOT_API_TOKEN_HERE"

auth_tokens:
  - token: "admin-GENERATE_WITH_openssl_rand_hex_32"
    description: "Admin"
    permissions:
      ryot: { actions: ["*"] }
